annotations: []
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: Router01
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        type: physical
        slot: 3
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: ext-conn-0
    node_definition: external_connector
    parameters: {}
    ram: null
    tags: []
    x: 360
    y: 0
    interfaces:
      - id: i0
        label: port
        mac_address: null
        type: physical
        slot: 0
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: Switch01
    node_definition: catalyst9000v_uadp
    parameters: {}
    ram: null
    tags: []
    x: 200
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        type: physical
        slot: 0
      - id: i2
        label: GigabitEthernet1/0/1
        mac_address: null
        type: physical
        slot: 1
      - id: i3
        label: GigabitEthernet1/0/2
        mac_address: null
        type: physical
        slot: 2
      - id: i4
        label: GigabitEthernet1/0/3
        mac_address: null
        type: physical
        slot: 3
      - id: i5
        label: GigabitEthernet1/0/4
        mac_address: null
        type: physical
        slot: 4
      - id: i6
        label: GigabitEthernet1/0/5
        mac_address: null
        type: physical
        slot: 5
      - id: i7
        label: GigabitEthernet1/0/6
        mac_address: null
        type: physical
        slot: 6
      - id: i8
        label: GigabitEthernet1/0/7
        mac_address: null
        type: physical
        slot: 7
      - id: i9
        label: GigabitEthernet1/0/8
        mac_address: null
        type: physical
        slot: 8
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: mgmt-sw
    node_definition: unmanaged_switch
    parameters: {}
    ram: null
    tags: []
    x: 80
    y: 0
    interfaces:
      - id: i0
        label: port0
        mac_address: null
        type: physical
        slot: 0
      - id: i1
        label: port1
        mac_address: null
        type: physical
        slot: 1
      - id: i2
        label: port2
        mac_address: null
        type: physical
        slot: 2
      - id: i3
        label: port3
        mac_address: null
        type: physical
        slot: 3
      - id: i4
        label: port4
        mac_address: null
        type: physical
        slot: 4
      - id: i5
        label: port5
        mac_address: null
        type: physical
        slot: 5
      - id: i6
        label: port6
        mac_address: null
        type: physical
        slot: 6
      - id: i7
        label: port7
        mac_address: null
        type: physical
        slot: 7
links:
  - id: l0
    n1: n2
    n2: n3
    i1: i1
    i2: i0
    conditioning: {}
    label: cat9kvuadp-0-GigabitEthernet0/0<->unmanaged-switch-0-port0
  - id: l1
    n1: n0
    n2: n3
    i1: i1
    i2: i1
    conditioning: {}
    label: cat8000v-0-GigabitEthernet1<->unmanaged-switch-0-port1
  - id: l2
    n1: n3
    n2: n1
    i1: i2
    i2: i0
    conditioning: {}
    label: unmanaged-switch-0-port2<->ext-conn-0-port
  - id: l3
    n1: n0
    n2: n2
    i1: i2
    i2: i2
    conditioning: {}
    label: cat8000v-0-GigabitEthernet2<->cat9kvuadp-0-GigabitEthernet1/0/1
lab:
  description: ''
  notes: ''
  title: TF - Topo Automation
  version: 0.3.0
